#!/usr/bin/env bash

set -e

export MASTER_IP=`getent ahostsv4 "master-1.node.paas.labs.stratio.com" | head -n1 | awk '{print $1}'`

if [[ -e environments/$ENVIRONMENT.pem ]]; then
	export PEM_FILE_ARG="-i environments/$ENVIRONMENT.pem"
fi
	
sshpass -p "${EOS_BOOTSTRAP_PASSWORD}" \
	ssh -ttt $PEM_FILE_ARG -o StrictHostKeyChecking=no ${EOS_BOOTSTRAP_USER}@$MASTER_IP \
	sudo cat /opt/mesosphere/etc/mesos/security/credentials.json | jq .

