#!/usr/bin/env bash

set -e

if [[ "$1" == "" ]]; then
	echo "usage:tail-task-log {task-name} [{file}]"
	exit -1
fi

if [[ -z "$service" ]]; then
	export service=$FRAMEWORK
fi

taskName="$1"
shift

if [[ "$1" == "" ]]; then
	file=stdout
fi

frameworkId=`dcos service --json | jq -r --arg serviceName $service '.[] | select(.name==$serviceName).id' | tail -n1`

taskId=`dcos task --json | jq -r --arg frameworkId $frameworkId --arg taskName $taskName '.[] | select(.framework_id==$frameworkId and .name==$taskName).id'`

if [[ "$taskId" != "" ]]; then
	(set -x && dcos task log "$taskId" $@ $file)
else 
	echo "no taskId found for service: $service and task: $taskName"
fi