#!/usr/bin/env bash

CURDIR=`dirname "$0"`
cd "$CURDIR"

if [[ "$FRAMEWORK" == "" ]]; then
	echo "please set -fw parameter"
else
	set -e
	cd paas-secret-utils

	cat "$HOME"/frameworks/$FRAMEWORK.certs.list > "certs.list"
	cat "$HOME"/frameworks/$FRAMEWORK.pass.list > "pass.list"
	cat "$HOME"/frameworks/$FRAMEWORK.krb.list > "krb.list"

	./gencerts \
	 -v "$VAULT_HOSTS" \
	 -o "$VAULT_PORT" \
	 -t "$VAULT_TOKEN" \
	 -l certs.list \
	 -p stratio

	./genpass -l pass.list -v "$VAULT_HOSTS" -p "$VAULT_PORT" -t "$VAULT_TOKEN"

	./genktabs \
	 -r "$KRB_REALM" \
	 -s "$KRB_ADMIN_HOST" \
	 -p "$VAULT_PORT" \
	 -t "$VAULT_TOKEN" \
	 -v "$VAULT_HOSTS" \
	 -l "krb.list" \
	 -a "stratio/listonly" \
	 -k "stratio_listonly.keytab"

fi